const courseList = [
  "Engineering Chemistry",
  "Engineering Chemistry Lab",
  "Computer Programming: Python",
  "Structured and Object-Oriented Programming",
  "Structured and Object-Oriented Programming Lab",
  "Computer Programming: Java",
  "Basic Electrical and Electronics Engineering",
  "Basic Electrical and Electronics Engineering Lab",
  "Technical English Communication",
  "Technical English Communication Lab",
  "Technical Report Writing",
  "Calculus",
  "Calculus Lab",
  "Differential Equations and Transforms",
  "Complex Variables and Linear Algebra",
  "Probability and Statistics",
  "Probability and Statistics Lab",
  "Engineering Physics",
  "Engineering Physics Lab",
  "Quantitative Skills Practice I",
  "Quantitative Skills Practice II",
  "Qualitative Skills Practice I",
  "Qualitative Skills Practice II",
  "Digital Systems Design",
  "Digital Systems Design Lab",
  "Microprocessors and Microcontrollers",
  "Microprocessors and Microcontrollers Lab",
  "Discrete Mathematics and Graph Theory",
  "Data Structures and Algorithms",
  "Data Structures and Algorithms Lab",
  "Web Programming",
  "Design and Analysis of Algorithms",
  "Design and Analysis of Algorithms Lab",
  "Computer Architecture and Organization",
  "Software Engineering",
  "Software Engineering Lab",
  "Database Systems",
  "Database Systems Lab",
  "Operating Systems",
  "Operating Systems Lab",
  "Theory of Computation",
  "Embedded Systems",
  "Artificial Intelligence",
  "Compiler Design",
  "Compiler Design Lab",
  "Computer Networks",
  "Computer Networks Lab",
  "Cryptography and Network Security",
  "Cryptography and Network Security Lab",
  "Advances in Programming Language Concepts",
  "Advances in Programming Language Concepts Lab",
  "Software Project Management",
  "Software Project Management Lab",
  "Image Processing",
  "Image Processing Lab",
  "Information Retrieval Systems",
  "Information Retrieval Systems Lab",
  "Computer Graphics",
  "Computer Graphics Lab",
  "Applied Linear Algebra",
  "Practical Machine Learning",
  "Practical Machine Learning Lab",
  "Data Mining",
  "Data Mining Lab",
  "Natural Language Processing",
  "Natural Language Processing Lab",
  "Game Theory",
  "Graph Theory",
  "Computational Geometry",
  "Optimization Techniques",
  "Parallel and Distributed Systems",
  "Parallel and Distributed Systems Lab",
  "Information Security",
  "Information Security Lab",
  "Distributed Systems",
  "Distributed Systems Lab",
  "Cloud Computing",
  "Cloud Computing Lab",
  "Machine Learning",
  "Machine Learning Lab",
  "Deep Learning",
  "Deep Learning Lab",
  "Blockchain Technology",
  "Blockchain Technology Lab",
  "Quantum Computing",
  "Internet of Things",
  "Internet of Things Lab",
  "Augmented and Virtual Reality",
  "Human Computer Interaction",
  "Mobile Application Development",
  "Mobile Application Development Lab",
  "Software Testing",
  "Software Testing Lab",
  "DevOps",
  "DevOps Lab",
  "Big Data Analytics",
  "Big Data Analytics Lab",
  "Cyber Security",
  "Cyber Security Lab",
  "Digital Forensics",
  "Digital Forensics Lab",
  "Ethical Hacking",
  "Ethical Hacking Lab",
  "Bioinformatics",
  "Bioinformatics Lab",
  "Computational Biology",
  "Computational Biology Lab",
  "Computer Vision",
  "Computer Vision Lab",
  "Robotics",
  "Robotics Lab",
  "Speech Processing",
  "Speech Processing Lab",
  "Social Network Analysis",
  "Recommender Systems",
  "Web Mining",
  "Text Mining",
  "Pattern Recognition",
  "Pattern Recognition Lab",
  "Neural Networks",
  "Neural Networks Lab",
  "Fuzzy Logic",
  "Genetic Algorithms",
  "Swarm Intelligence",
  "Evolutionary Computing",
  "Expert Systems",
  "Knowledge Representation",
  "Automated Reasoning",
  "Multi-Agent Systems",
  "Cognitive Computing",
  "Ambient Intelligence",
  "Pervasive Computing",
  "Grid Computing",
  "High Performance Computing",
  "Service Oriented Architecture",
  "Enterprise Application Integration",
  "Business Intelligence",
  "Data Warehousing",
  "OLAP and Data Mining",
  "E-Commerce Technology",
  "Digital Marketing",
  "IT Service Management",
  "IT Governance",
  "Project Management",
  "Agile Methodologies",
  "Lean Software Development",
  "Software Architecture",
  "Design Patterns",
  "Microservices Architecture",
  "API Design and Development",
  "Frontend Technologies",
  "Backend Technologies",
  "Full Stack Development",
  "Database Administration",
  "Network Administration",
  "System Administration",
  "IT Infrastructure Management",
  "Corporate Finance",
  "Financial Statement Analysis",
  "Cost and Management Accounting",
  "Mind",
  "Health Humanities in Biotechnological Era",
  "Reproductive Choices for a Sustainable Society",
  "Introduction to Sustainable Aging",
  "Environmental Psychology",
  "Indian Psychology",
  "Psychology of Wellness",
  "Entrepreneurship",
  "Advanced Competitive Coding - I",
  "Advanced Competitive Coding - II",
  "Effective English Communication"
];

// Create subjects array with 'All Subjects' option
export const subjects = ['All Subjects', ...courseList];

export default courseList;